import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseMapping } from '@/adapters/reaper/mapping'
import { loadActions, ActionIndex } from '@/adapters/reaper/actions'
import { renderKeybindingsDoc } from '@/adapters/reaper/keybindings-doc'

const idx = new ActionIndex(loadActions())
const luna = parseMapping(readFileSync(fileURLToPath(new URL('../mappings/luna.toml', import.meta.url)), 'utf8'))

describe('renderKeybindingsDoc', () => {
  it('renders both platform labels for the same bits', () => {
    const m = parseMapping('[meta]\nname="x"\n[[binding]]\nluna="Copy"\nkey="Cmd+C"\naction=40057\n')
    const doc = renderKeybindingsDoc(m, idx)
    expect(doc).toContain('`Cmd+C`')
    expect(doc).toContain('`Ctrl+C`')
  })

  it('resolves ids to real action names rather than printing bare numbers', () => {
    const m = parseMapping('[meta]\nname="x"\n[[binding]]\nluna="Mute"\nkey="B"\nrazor_slice=40175\n')
    expect(renderKeybindingsDoc(m, idx)).toContain('Item properties: Toggle mute')
  })

  it('files natively razor-aware actions under the edit area, not "everything else"', () => {
    // Delete/Cut carry no wrapper but do honor the area, so a reader must not
    // conclude from this doc that they are ordinary whole-clip operations.
    const doc = renderKeybindingsDoc(luna, idx)
    const areaSection = doc.slice(doc.indexOf('## The 2D edit area'), doc.indexOf('## Everything else'))
    expect(areaSection).toContain('Clear')
    expect(areaSection).toContain('Cut')
    expect(areaSection).toContain('acts on the area natively')
  })

  it('distinguishes area-scoped from whole-clip wrappers', () => {
    const doc = renderKeybindingsDoc(luna, idx)
    expect(doc).toContain('split at the area edges → select what’s inside → '.replace('’', "'"))
    expect(doc).toContain("select the area's items → ")
  })

  it('lists the deliberate gaps rather than hiding them', () => {
    const doc = renderKeybindingsDoc(luna, idx)
    expect(doc).toContain('## Deliberately unmapped')
    expect(doc).toContain('Create Bus')
  })

  it('marks itself generated so nobody hand-edits it', () => {
    expect(renderKeybindingsDoc(luna, idx)).toContain('GENERATED by `pnpm ra docs`')
  })

  it('escapes pipes so a key label can never break the table', () => {
    const m = parseMapping('[meta]\nname="x"\n[[binding]]\nluna="Pipe|Name"\nkey="B"\naction=40057\n')
    const doc = renderKeybindingsDoc(m, idx)
    expect(doc).toContain('Pipe\\|Name')
  })
})
