import { debugHook } from '@/adapters/reaper/debug-runtime'

// LUNA reload button. A generated ReaScript, bound to a key (or dropped on a
// toolbar), that rebuilds + reinstalls the whole keymap in one press from inside
// REAPER -- no terminal, no manual import dance for the common case.
//
// It shells out to `pnpm ra refresh` through a LOGIN shell (`/bin/sh -lc`),
// because a macOS GUI app does not inherit the interactive shell PATH, so a bare
// `pnpm` would not be found. The repo root is baked at build time.
//
// Script bodies are picked up by REAPER the moment `install` copies them (REAPER
// re-reads a ReaScript from disk on every run), so a script change is live
// immediately. Only a *key binding* change needs a one-time re-import -- REAPER
// only reads reaper-kb.ini at startup and has no API to import a specific keymap
// file. `refresh` reports which case happened; this button relays it.
export function renderReloadScript(opts: { repoRoot: string; spec: string; pathPrefix?: string }): string {
  const { repoRoot, spec } = opts
  const pathPrefix = opts.pathPrefix ?? ''
  // Long-bracket literals avoid any quote/backslash escaping of the paths.
  const bakedRepo = `[==[${repoRoot}]==]`
  const bakedPath = `[==[${pathPrefix}]==]`
  return `-- LUNA: Reload (rebuild + reinstall from inside REAPER)
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
${debugHook('reload')}

local repo = ${bakedRepo}
-- A macOS GUI app does not inherit the interactive shell PATH, and a login
-- /bin/sh does not read ~/.zshrc, so pnpm/node (e.g. under nvm) are invisible.
-- The node/pnpm bin dir, detected at build time, is prepended here.
local pathPrefix = ${bakedPath}

local function run()
  local exportPath = (pathPrefix ~= "") and ("export PATH=\\"" .. pathPrefix .. ":$PATH\\"; ") or ""
  local cmd = "/bin/sh -lc '" .. exportPath .. "cd \\"" .. repo .. "\\" && pnpm ra refresh 2>&1'"
  local out = reaper.ExecProcess(cmd, 120000)
  if not out then
    _log("exec_failed repo=" .. repo)
    reaper.ShowMessageBox("LUNA reload could not start (ExecProcess failed).\\nRepo: " .. repo, "LUNA reload", 0)
    return
  end

  local nl = out:find("\\n")
  local code = tonumber(nl and out:sub(1, nl - 1) or out) or -1
  local body = nl and out:sub(nl + 1) or ""
  local bindingsChanged = body:find("BINDINGS: changed", 1, true) ~= nil

  if code ~= 0 then
    _log("refresh_FAILED code=" .. tostring(code))
    reaper.ShowMessageBox("LUNA reload FAILED (exit " .. tostring(code) .. ").\\n\\n" .. body, "LUNA reload", 0)
    return
  end

  if bindingsChanged then
    _log("refresh_ok bindings=changed")
    reaper.ShowMessageBox(
      "Reloaded. Scripts are live now.\\n\\nKey bindings CHANGED -- re-import once:\\nActions > Show action list > Key map > Import > LUNA (Pro Tools).",
      "LUNA reload", 0)
  else
    _log("refresh_ok bindings=unchanged")
    reaper.ShowMessageBox("Reloaded. Scripts are live now.\\nBindings unchanged -- nothing else to do.", "LUNA reload", 0)
  end
end

run()
`
}
