#!/usr/bin/env python3
"""Build a .ReaperKeyMap from a declarative TOML mapping table.

    tools/build_keymap.py mappings/luna-linux.toml -o build/luna-linux.ReaperKeyMap

Every binding is validated against the action list dumped from REAPER itself
(data/reaper-actions-7.78-linux.tsv), so a typo'd command ID fails the build
rather than silently producing a dead key.
"""
import argparse
import hashlib
import pathlib
import sys
import tomllib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import keyspec  # noqa: E402
from find_action import load as load_actions  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SECTION_MAIN = 0

# Subdirectory under REAPER's Scripts/ that generated ReaScripts install into.
SCRIPT_DIR = "luna"

EXTEND_TEMPLATE = '''\
-- {label}
-- Generated by reaper-automation from {spec}. Do not hand-edit.
--
-- Extends the time selection to wherever action {move} ({move_name})
-- lands the edit cursor, keeping the far edge anchored so repeated presses keep
-- extending. This is LUNA / Pro Tools "hold Shift while moving the transport".
--
-- A plain custom action cannot do this: it would re-anchor on every press, so
-- the second press would replace the selection instead of growing it.

local MOVE = {move}

local function extend()
  local sel_start, sel_end = reaper.GetSet_LoopTimeRange(false, false, 0, 0, false)
  local cursor = reaper.GetCursorPosition()

  -- Anchor the edge we are moving away from. With no selection yet, anchor here.
  local anchor
  if sel_start == sel_end then
    anchor = cursor
  elseif math.abs(cursor - sel_end) < math.abs(cursor - sel_start) then
    anchor = sel_start
  else
    anchor = sel_end
  end

  reaper.Main_OnCommand(MOVE, 0)
  local dest = reaper.GetCursorPosition()

  if dest == anchor then
    reaper.GetSet_LoopTimeRange(true, false, 0, 0, false)
  else
    reaper.GetSet_LoopTimeRange(true, false, math.min(anchor, dest), math.max(anchor, dest), false)
  end
end

reaper.PreventUIRefresh(1)
extend()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
'''


def stable_id(label):
    """Deterministic custom-action ID, so rebuilds don't churn the file."""
    return hashlib.md5(("reaper-automation/" + label).encode()).hexdigest()


def slugify(text):
    out = "".join(c.lower() if c.isalnum() else "_" for c in text)
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_")


def build(spec_path, out_path, strict=True):
    spec = tomllib.loads(pathlib.Path(spec_path).read_text())
    meta = spec.get("meta", {})
    bindings = spec.get("binding", [])

    actions = {r["command_id"]: r["name"] for r in load_actions() if r["section"] == "main"}

    act_lines, scr_lines, key_lines, errors = [], [], [], []
    stats = {"direct": 0, "macro": 0, "script": 0, "disabled": 0, "unmapped": 0}
    seen_keys = {}
    seen_macros = {}
    scripts = {}  # filename -> lua source
    seen_scripts = {}  # move action id -> (filename, script id)

    for b in bindings:
        luna = b.get("luna", "<unnamed>")
        status = b.get("status", "ok")

        if status == "unmapped":
            stats["unmapped"] += 1
            continue

        try:
            flags, code = keyspec.parse(b["key"])
        except (keyspec.KeySpecError, KeyError) as e:
            errors.append(f"{luna}: {e}")
            continue

        combo = keyspec.describe(flags, code)
        if (flags, code) in seen_keys:
            errors.append(f"{luna}: key {combo} already bound to {seen_keys[(flags, code)]!r}")
            continue
        seen_keys[(flags, code)] = luna

        if "extend" in b:
            move = str(b["extend"])
            if move not in actions:
                errors.append(f"{luna}: extend references unknown action {move}")
                continue
            # One script per move action -- LUNA's numpad alternates share a script.
            if move in seen_scripts:
                fname, sid = seen_scripts[move]
            else:
                base = b.get("label", luna.split(" (")[0])
                label = f"LUNA: {base}"
                fname = f"luna_{slugify(base)}.lua"
                sid = stable_id(label)
                scripts[fname] = EXTEND_TEMPLATE.format(
                    label=label,
                    spec=pathlib.Path(spec_path).name,
                    move=move,
                    move_name=actions[move],
                )
                scr_lines.append(
                    f'SCR 4 {SECTION_MAIN} "{sid}" "Custom: {label}" {SCRIPT_DIR}/{fname}'
                )
                seen_scripts[move] = (fname, sid)
            command = "_" + sid
            desc = f"script {fname}  [extend selection via {actions[move]}]"
            stats["script"] += 1
        elif "macro" in b:
            steps = [str(s) for s in b["macro"]]
            missing = [s for s in steps if s not in actions]
            if missing:
                errors.append(f"{luna}: macro references unknown action(s) {missing}")
                continue
            label = b.get("label", f"LUNA: {luna}")
            mid = seen_macros.get(label) or stable_id(label)
            if label not in seen_macros:
                seen_macros[label] = mid
                act_lines.append(
                    f'ACT 0 {SECTION_MAIN} "{mid}" "Custom: {label}" ' + " ".join(steps)
                )
            command = "_" + mid
            desc = label + "  [" + " > ".join(actions[s] for s in steps) + "]"
            stats["macro"] += 1
        elif "action" in b:
            cid = str(b["action"])
            if cid not in actions:
                errors.append(f"{luna}: unknown command id {cid}")
                continue
            command = cid
            desc = actions[cid]
            stats["direct"] += 1
        elif status == "disable":
            command = "0"
            desc = "DISABLE REAPER DEFAULT"
            stats["disabled"] += 1
        else:
            errors.append(f"{luna}: needs one of action / macro / status")
            continue

        key_lines.append(f"KEY {flags} {code} {command} {SECTION_MAIN}\t# {combo} : {luna} -> {desc}")

    if errors:
        for e in errors:
            print(f"ERROR  {e}", file=sys.stderr)
        if strict:
            print(f"\n{len(errors)} error(s); nothing written.", file=sys.stderr)
            return 1

    header = [
        f"# {meta.get('name', 'REAPER keymap')}",
        f"# generated by reaper-automation from {pathlib.Path(spec_path).name} -- do not hand-edit",
        f"# target: {meta.get('target', '?')}   REAPER: {meta.get('reaper_version', '?')}",
        "#",
        "# Import via: Actions > Show action list > Key map > Import...",
    ]
    for line in meta.get("notes", []):
        header.append(f"# {line}")

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    preamble = scr_lines + act_lines
    body = header + [""] + preamble + ([""] if preamble else []) + key_lines
    out.write_text("\n".join(body) + "\n")

    # ReaScripts live alongside the keymap; install.py copies both into place.
    script_out = out.parent / "Scripts" / SCRIPT_DIR
    if scripts:
        script_out.mkdir(parents=True, exist_ok=True)
        for fname, src in sorted(scripts.items()):
            (script_out / fname).write_text(src)

    total = stats["direct"] + stats["macro"] + stats["script"] + stats["disabled"]
    print(f"wrote {out}")
    print(
        f"  {total} bindings  "
        f"({stats['direct']} direct, {stats['macro']} macro, "
        f"{stats['script']} script, {stats['disabled']} disabled)  "
        f"+ {len(act_lines)} custom actions"
    )
    if scripts:
        print(f"  {len(scripts)} ReaScript(s) -> {script_out}")
    if stats["unmapped"]:
        print(f"  {stats['unmapped']} LUNA shortcut(s) left unmapped (status = \"unmapped\")")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--no-strict", action="store_true", help="write output even if validation fails")
    args = ap.parse_args()
    return build(args.spec, args.out, strict=not args.no_strict)


if __name__ == "__main__":
    sys.exit(main())
