#!/usr/bin/env python3
"""Build a .ReaperKeyMap from a declarative TOML mapping table.

    tools/build_keymap.py mappings/luna-linux.toml -o build/luna-linux.ReaperKeyMap

Every binding is validated against the action list dumped from REAPER itself
(data/reaper-actions-7.78-linux.tsv), so a typo'd command ID fails the build
rather than silently producing a dead key.
"""
import argparse
import hashlib
import pathlib
import sys
import tomllib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import keyspec  # noqa: E402
from find_action import load as load_actions  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SECTION_MAIN = 0


def stable_id(label):
    """Deterministic custom-action ID, so rebuilds don't churn the file."""
    return hashlib.md5(("reaper-automation/" + label).encode()).hexdigest()


def build(spec_path, out_path, strict=True):
    spec = tomllib.loads(pathlib.Path(spec_path).read_text())
    meta = spec.get("meta", {})
    bindings = spec.get("binding", [])

    actions = {r["command_id"]: r["name"] for r in load_actions() if r["section"] == "main"}

    act_lines, key_lines, errors = [], [], []
    stats = {"direct": 0, "macro": 0, "disabled": 0, "unmapped": 0}
    seen_keys = {}
    seen_macros = {}

    for b in bindings:
        luna = b.get("luna", "<unnamed>")
        status = b.get("status", "ok")

        if status == "unmapped":
            stats["unmapped"] += 1
            continue

        try:
            flags, code = keyspec.parse(b["key"])
        except (keyspec.KeySpecError, KeyError) as e:
            errors.append(f"{luna}: {e}")
            continue

        combo = keyspec.describe(flags, code)
        if (flags, code) in seen_keys:
            errors.append(f"{luna}: key {combo} already bound to {seen_keys[(flags, code)]!r}")
            continue
        seen_keys[(flags, code)] = luna

        if "macro" in b:
            steps = [str(s) for s in b["macro"]]
            missing = [s for s in steps if s not in actions]
            if missing:
                errors.append(f"{luna}: macro references unknown action(s) {missing}")
                continue
            label = b.get("label", f"LUNA: {luna}")
            mid = seen_macros.get(label) or stable_id(label)
            if label not in seen_macros:
                seen_macros[label] = mid
                act_lines.append(
                    f'ACT 0 {SECTION_MAIN} "{mid}" "Custom: {label}" ' + " ".join(steps)
                )
            command = "_" + mid
            desc = label + "  [" + " > ".join(actions[s] for s in steps) + "]"
            stats["macro"] += 1
        elif "action" in b:
            cid = str(b["action"])
            if cid not in actions:
                errors.append(f"{luna}: unknown command id {cid}")
                continue
            command = cid
            desc = actions[cid]
            stats["direct"] += 1
        elif status == "disable":
            command = "0"
            desc = "DISABLE REAPER DEFAULT"
            stats["disabled"] += 1
        else:
            errors.append(f"{luna}: needs one of action / macro / status")
            continue

        key_lines.append(f"KEY {flags} {code} {command} {SECTION_MAIN}\t# {combo} : {luna} -> {desc}")

    if errors:
        for e in errors:
            print(f"ERROR  {e}", file=sys.stderr)
        if strict:
            print(f"\n{len(errors)} error(s); nothing written.", file=sys.stderr)
            return 1

    header = [
        f"# {meta.get('name', 'REAPER keymap')}",
        f"# generated by reaper-automation from {pathlib.Path(spec_path).name} -- do not hand-edit",
        f"# target: {meta.get('target', '?')}   REAPER: {meta.get('reaper_version', '?')}",
        "#",
        "# Import via: Actions > Show action list > Key map > Import...",
    ]
    for line in meta.get("notes", []):
        header.append(f"# {line}")

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = header + [""] + act_lines + ([""] if act_lines else []) + key_lines
    out.write_text("\n".join(body) + "\n")

    total = stats["direct"] + stats["macro"] + stats["disabled"]
    print(f"wrote {out}")
    print(
        f"  {total} bindings  "
        f"({stats['direct']} direct, {stats['macro']} macro, {stats['disabled']} disabled)  "
        f"+ {len(act_lines)} custom actions"
    )
    if stats["unmapped"]:
        print(f"  {stats['unmapped']} LUNA shortcut(s) left unmapped (status = \"unmapped\")")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--no-strict", action="store_true", help="write output even if validation fails")
    args = ap.parse_args()
    return build(args.spec, args.out, strict=not args.no_strict)


if __name__ == "__main__":
    sys.exit(main())
