import { parse as parseKey, describe as describeKey } from '@/keyspec'
import { superWarning, type Target } from '@/translate'
import { stableId, slugify } from '@/ids'
import type { ActionIndex } from '@/actions'
import type { Binding, Mapping } from '@/mapping'
import { renderExtendScript } from '@/extend-template'

const SECTION_MAIN = 0
const SCRIPT_DIR = 'luna'

export interface BuildResult {
  keymapText: string
  scripts: Map<string, string>
  warnings: string[]
  stats: { direct: number; macro: number; script: number; disabled: number; unmapped: number }
}

export function buildKeymap(mapping: Mapping, actions: ActionIndex, target: Target): BuildResult {
  const actLines: string[] = []
  const scrLines: string[] = []
  const keyLines: string[] = []
  const errors: string[] = []
  const warnings: string[] = []
  const stats = { direct: 0, macro: 0, script: 0, disabled: 0, unmapped: 0 }

  const seenKeys = new Map<string, string>()
  const seenMacros = new Map<string, string>()
  const seenScripts = new Map<number, { fname: string; sid: string }>()
  const scripts = new Map<string, string>()

  for (const b of mapping.bindings) {
    const luna = b.luna
    if (b.status === 'unmapped') { stats.unmapped++; continue }

    let flags: number
    let code: number
    try {
      const p = parseKey(b.key as string)
      flags = p.flags; code = p.keycode
    } catch (e) {
      errors.push(`${luna}: ${(e as Error).message}`)
      continue
    }

    const combo = describeKey(flags, code, target)
    const comboKey = `${flags},${code}`
    if (seenKeys.has(comboKey)) {
      errors.push(`${luna}: key ${combo} already bound to ${JSON.stringify(seenKeys.get(comboKey))}`)
      continue
    }
    seenKeys.set(comboKey, luna)

    const w = superWarning(flags, target, luna)
    if (w) warnings.push(w)

    let command: string
    let desc: string

    if (b.kind && 'extend' in b.kind) {
      const move = b.kind.extend
      const moveName = actions.byId(String(move))
      if (moveName === undefined) { errors.push(`${luna}: extend references unknown action ${move}`); continue }
      let entry = seenScripts.get(move)
      if (!entry) {
        const base = b.label ?? luna.split(' (')[0]
        const label = `LUNA: ${base}`
        const fname = `luna_${slugify(base)}.lua`
        const sid = stableId(label)
        scripts.set(fname, renderExtendScript({ label, spec: mapping.meta.name, move, moveName }))
        scrLines.push(`SCR 4 ${SECTION_MAIN} "${sid}" "Custom: ${label}" ${SCRIPT_DIR}/${fname}`)
        entry = { fname, sid }
        seenScripts.set(move, entry)
      }
      command = '_' + entry.sid
      desc = `script ${entry.fname}  [extend selection via ${moveName}]`
      stats.script++
    } else if (b.kind && 'macro' in b.kind) {
      const steps = b.kind.macro.map(String)
      const missing = steps.filter((s) => !actions.has(s))
      if (missing.length) { errors.push(`${luna}: macro references unknown action(s) ${JSON.stringify(missing)}`); continue }
      const label = b.label ?? `LUNA: ${luna}`
      let mid = seenMacros.get(label)
      if (mid === undefined) {
        mid = stableId(label)
        seenMacros.set(label, mid)
        actLines.push(`ACT 0 ${SECTION_MAIN} "${mid}" "Custom: ${label}" ${steps.join(' ')}`)
      }
      command = '_' + mid
      desc = `${label}  [${steps.map((s) => actions.byId(s)).join(' > ')}]`
      stats.macro++
    } else if (b.kind && 'action' in b.kind) {
      const cid = String(b.kind.action)
      const name = actions.byId(cid)
      if (name === undefined) { errors.push(`${luna}: unknown command id ${cid}`); continue }
      command = cid
      desc = name
      stats.direct++
    } else if (b.status === 'disable') {
      command = '0'
      desc = 'DISABLE REAPER DEFAULT'
      stats.disabled++
    } else {
      errors.push(`${luna}: needs one of action / macro / status`)
      continue
    }

    keyLines.push(`KEY ${flags} ${code} ${command} ${SECTION_MAIN}\t# ${combo} : ${luna} -> ${desc}`)
  }

  if (errors.length) {
    throw new Error(`${errors.length} error(s):\n` + errors.map((e) => `  ERROR  ${e}`).join('\n'))
  }

  const m = mapping.meta
  const header = [
    `# ${m.name}`,
    `# generated by reaper-automation from ${m.name} -- do not hand-edit`,
    `# target: ${target}   REAPER: ${m.reaperVersion ?? '?'}`,
    '#',
    '# Import via: Actions > Show action list > Key map > Import...',
    ...m.notes.map((line) => `# ${line}`),
  ]
  const preamble = [...scrLines, ...actLines]
  const body = [...header, '', ...preamble, ...(preamble.length ? [''] : []), ...keyLines]
  const keymapText = body.join('\n') + '\n'

  return { keymapText, scripts, warnings, stats }
}
