// Runtime debug-logging support for the generated ReaScripts.
//
// Two generated-but-runtime-only Lua files (never referenced by an SCR line, so
// they don't affect keymap bytes) sit alongside the action scripts in
// `Scripts/luna/`:
//
//   luna_debug.lua  -- shared module: appends capped, timestamped lines to
//                      <resource>/luna-debug.log, tagging each with the version stamp
//   luna_stamp.lua  -- one line: `return "<stamp>"`, the git stamp baked at build time
//
// Every generated action script gets a `debugHook(...)` prelude that loads the
// shared module (pcall-guarded, so a missing/broken module never breaks the
// action) and exposes a local `_log(fields)` helper.

export const DEBUG_MODULE_FILE = 'luna_debug.lua'
export const STAMP_MODULE_FILE = 'luna_stamp.lua'

function luaQuote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"'
}

/** `luna_stamp.lua` -- returns the build-time version stamp as a Lua string. */
export function renderStampModule(stamp: string): string {
  return `-- LUNA version stamp. Generated by reaper-automation. Do not hand-edit.\nreturn ${luaQuote(stamp)}\n`
}

/**
 * `luna_debug.lua` -- the shared logging module. Constant (no per-build data),
 * so it never affects reproducibility. Derives the log path and the sibling
 * stamp module from its own on-disk location.
 */
export function renderDebugModule(): string {
  return `-- LUNA debug logging. Shared runtime module, loaded by generated scripts via dofile.
-- Generated by reaper-automation. Do not hand-edit.
--
-- Appends capped, timestamped lines to <resource>/luna-debug.log so a human (or
-- an agent) can see which script fired, at which version stamp, and what it did.

local M = {}
local sep = package.config:sub(1, 1)

local function moduleDir()
  local src = debug.getinfo(1, "S").source:gsub("^@", "")
  return src:match("^(.*" .. sep .. ")") or ("." .. sep)
end

local DIR = moduleDir()
-- luna_debug.lua lives at <resource>/Scripts/luna/; the log sits at the resource root.
local LOG = DIR .. ".." .. sep .. ".." .. sep .. "luna-debug.log"
local CAP = 1024 * 1024 -- trim the log to its last ~1MB on write

local function stamp()
  local ok, s = pcall(dofile, DIR .. "${STAMP_MODULE_FILE}")
  if ok and type(s) == "string" then return s end
  return "unknown"
end

local function trim()
  local f = io.open(LOG, "rb")
  if not f then return end
  local size = f:seek("end")
  if size <= CAP then f:close() return end
  f:seek("set", size - CAP)
  local tail = f:read("*a")
  f:close()
  tail = tail:gsub("^[^\\n]*\\n", "") -- drop the partial first line
  local w = io.open(LOG, "wb")
  if w then w:write(tail); w:close() end
end

function M.log(script, fields)
  trim()
  local f = io.open(LOG, "a")
  if not f then return end
  f:write(os.date("!%Y-%m-%dT%H:%M:%S"), "  ", tostring(script), "  sha=", stamp(), "  ", tostring(fields or ""), "\\n")
  f:close()
end

return M
`
}

/**
 * The prelude injected at the top of each generated action script. Resolves the
 * sibling `luna_debug.lua` from the running action's own path and defines a
 * local `_log(fields)` tagged with `scriptKey`. Everything is pcall-guarded so
 * logging can never break the action it is observing.
 */
export function debugHook(scriptKey: string): string {
  return `-- debug logging (pcall-guarded; never breaks the action)
local _src = select(2, reaper.get_action_context())
local _dir = (_src or ""):match("^(.*[/\\\\])") or ""
local _dok, _dbg = pcall(dofile, _dir .. "${DEBUG_MODULE_FILE}")
local function _log(fields)
  if _dok and _dbg then pcall(_dbg.log, "${scriptKey}", fields) end
end`
}
