export function renderExtendScript(opts: { label: string; spec: string; move: number; moveName: string }): string {
  const { label, spec, move, moveName } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- LUNA / Pro Tools "hold Shift while moving the transport": extend the time
-- selection using action ${move} (${moveName}), keeping the anchored edge
-- so repeated presses keep growing the selection. A forward move grows the END,
-- a backward move grows the START. In both cases the transport (edit cursor) is
-- left at the START of the selection, so playback begins at the selection start,
-- and loop/repeat is enabled so the selection plays back looped -- matching LUNA.
--
-- Direction is detected at runtime by probing the move, so the transport can sit
-- at the selection start without that position feeding back into which edge grows
-- (the old cursor-as-anchor scheme could not keep the transport at the start).
--
-- A plain custom action cannot do this: it would re-anchor on every press.

local MOVE = ${move}

local function extend()
  local sel_start, sel_end = reaper.GetSet_LoopTimeRange(false, false, 0, 0, false)
  local has_sel = sel_end > sel_start
  local origin = reaper.GetCursorPosition()

  -- Probe this move's direction (relative moves go forward/backward from anywhere;
  -- absolute jumps land before/after the origin). The probe result also seeds the
  -- first selection when none exists yet.
  reaper.Main_OnCommand(MOVE, 0)
  local probed = reaper.GetCursorPosition()

  if probed == origin then
    -- Move could not go any further; leave the selection as-is, park at its start.
    if has_sel then reaper.SetEditCurPos(sel_start, false, false) end
    return
  end

  local forward = probed > origin
  local new_start, new_end

  if not has_sel then
    new_start = math.min(origin, probed)
    new_end = math.max(origin, probed)
  elseif forward then
    -- Grow the END: run the move from the current end.
    reaper.SetEditCurPos(sel_end, false, false)
    reaper.Main_OnCommand(MOVE, 0)
    new_start = sel_start
    new_end = math.max(sel_start, reaper.GetCursorPosition())
  else
    -- Grow the START: run the move from the current start.
    reaper.SetEditCurPos(sel_start, false, false)
    reaper.Main_OnCommand(MOVE, 0)
    new_start = math.min(sel_end, reaper.GetCursorPosition())
    new_end = sel_end
  end

  reaper.GetSet_LoopTimeRange(true, false, new_start, new_end, false)
  reaper.SetEditCurPos(new_start, false, false)  -- transport at the selection start
  reaper.GetSetRepeat(1)                          -- enable loop, so the selection plays looped
end

reaper.PreventUIRefresh(1)
extend()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
`
}
