import { parse as parseKey, describe } from '@/keyspec'
import type { ActionIndex } from '@/actions'
import type { Binding, Mapping } from '@/mapping'

/**
 * KEYBINDINGS.md is generated from mappings/luna.toml, not hand-maintained: a
 * second hand-written copy of the mapping table is the one artifact in this repo
 * that could silently drift from the thing it documents. `ra docs --check`
 * fails when it has.
 */

function actionName(actions: ActionIndex, id: number): string {
  return actions.byId(String(id)) ?? `(unknown action ${id})`
}

/** Plain-language account of what a binding does, resolved to real action names. */
function mechanism(b: Binding, actions: ActionIndex): string {
  const k = b.kind
  if (!k) return '—'
  if ('action' in k) {
    const name = actionName(actions, k.action)
    return NATIVE_AREA_ACTIONS.has(k.action) ? `${name} (acts on the area natively)` : name
  }
  if ('macro' in k) return k.macro.map((id) => actionName(actions, id)).join(' → ')
  if ('extend' in k) return `script: extend the time selection via ${actionName(actions, k.extend)}`
  if ('razorExtend' in k) return `script: grow the 2D area via ${actionName(actions, k.razorExtend)}`
  if ('razorTrack' in k) return `${actionName(actions, k.razorTrack)} → repaint the area over the new track selection`
  if ('razor' in k) return `select the area's items → ${actionName(actions, k.razor)}`
  if ('razorSlice' in k) return `split at the area edges → select what's inside → ${actionName(actions, k.razorSlice)}`
  if ('separate' in k) return 'script: split at the area, else at the edit cursor'
  if ('tabTransient' in k) return `script: move the cursor to the ${k.tabTransient === 'next' ? 'next' : 'previous'} transient`
  return '—'
}

/**
 * REAPER actions that act on the razor area natively, so they need no wrapper.
 * Verified on REAPER 7.78 -- see docs/superpowers/specs/2026-08-16-razor-area-
 * substrate-design.md, "Verified primitives".
 */
const NATIVE_AREA_ACTIONS = new Set([40006, 40059, 40061, 40697, 40699])

/** True when the binding builds or acts on the 2D edit area. */
function isAreaBinding(b: Binding): boolean {
  const k = b.kind
  if (!k) return false
  // Delete and Cut carry no wrapper because they honor the area themselves;
  // they belong with the area ops regardless.
  if ('action' in k) return NATIVE_AREA_ACTIONS.has(k.action)
  return 'razorExtend' in k || 'razorTrack' in k || 'razor' in k || 'razorSlice' in k || 'separate' in k
}

function row(b: Binding, actions: ActionIndex): string {
  const { flags, keycode } = parseKey(b.key as string)
  const mac = describe(flags, keycode, 'macos')
  const linux = describe(flags, keycode, 'linux')
  const cell = (s: string) => s.replace(/\|/g, '\\|')
  return `| \`${cell(mac)}\` | \`${cell(linux)}\` | ${cell(b.luna)} | ${cell(mechanism(b, actions))} |`
}

export function renderKeybindingsDoc(mapping: Mapping, actions: ActionIndex): string {
  const active = mapping.bindings.filter((b) => b.status === 'ok' && b.key)
  const area = active.filter(isAreaBinding)
  const rest = active.filter((b) => !isAreaBinding(b))
  const unmapped = mapping.bindings.filter((b) => b.status === 'unmapped')
  const disabled = mapping.bindings.filter((b) => b.status === 'disable')

  const head = '| macOS | Linux | LUNA name | What it does |\n| --- | --- | --- | --- |'
  const out: string[] = []

  out.push('# Keybindings')
  out.push('')
  out.push('<!-- GENERATED by `pnpm ra docs` from mappings/luna.toml. Do not hand-edit. -->')
  out.push('')
  out.push(`Every combo this project binds, generated from \`mappings/luna.toml\`.`)
  out.push('')
  out.push('The two key columns are the same bits rendered per platform — REAPER stores')
  out.push('one modifier bitfield and only the *labels* differ (`+8` is Command on macOS')
  out.push('and Ctrl on Linux, `+16` is Option vs. Alt, `+32` is Control vs. Super).')
  out.push('')
  out.push(`Importing a key map overrides only the combos named here; REAPER's other`)
  out.push('defaults stay put. Key map → Reset to factory defaults backs it all out.')
  out.push('')
  out.push('## The 2D edit area')
  out.push('')
  out.push('These build the area or act on it. Per [CONSTITUTION.md](CONSTITUTION.md)')
  out.push("Principle 1, an operation acts on the data within the area's bounds and")
  out.push('clip boundaries play no part in scoping it.')
  out.push('')
  out.push(head)
  for (const b of area) out.push(row(b, actions))
  out.push('')
  out.push('## Everything else')
  out.push('')
  out.push(head)
  for (const b of rest) out.push(row(b, actions))

  if (unmapped.length) {
    out.push('')
    out.push('## Deliberately unmapped')
    out.push('')
    out.push('LUNA shortcuts left unbound rather than approximated. See the `comment` on')
    out.push('each in `mappings/luna.toml` for why.')
    out.push('')
    out.push('| LUNA name |')
    out.push('| --- |')
    for (const b of unmapped) out.push(`| ${b.luna} |`)
  }

  if (disabled.length) {
    out.push('')
    out.push('## Disabled')
    out.push('')
    out.push('| LUNA name |')
    out.push('| --- |')
    for (const b of disabled) out.push(`| ${b.luna} |`)
  }

  out.push('')
  return out.join('\n')
}
