export function renderRazorExtendScript(opts: { label: string; spec: string; move: number; moveName: string }): string {
  const { label, spec, move, moveName } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- LUNA / Pro Tools "hold Shift while moving the transport": extend the razor
-- edit area using action ${move} (${moveName}), keeping the anchored edge so
-- repeated presses keep growing the area. A forward move grows the END, a
-- backward move grows the START. In both cases the transport (edit cursor) is
-- left at the START of the area, so playback begins at the area start, and
-- loop/repeat is enabled so the area plays back looped -- matching LUNA.
--
-- Direction is detected at runtime by probing the move, so the transport can
-- sit at the area start without that position feeding back into which edge
-- grows (the old cursor-as-anchor scheme could not keep the transport at the
-- start). The area lives in P_RAZOREDITS (not the time selection) and, once
-- grown, is painted onto the currently selected tracks, clearing it from
-- unselected tracks -- the same scoping as the razor-repaint template.
--
-- A plain custom action cannot do this: it would re-anchor on every press.

local EPS = 1e-6
local MOVE = ${move}

local function readSpan()
  for i = 0, reaper.CountTracks(0) - 1 do
    local ok, s = reaper.GetSetMediaTrackInfo_String(reaper.GetTrack(0, i), "P_RAZOREDITS", "", false)
    if ok and s ~= "" then
      local a, b = s:match("([%d%.%-]+)%s+([%d%.%-]+)")
      if a and b then return tonumber(a), tonumber(b) end
    end
  end
  return nil
end

local function paint(a, b)
  local sel = {}
  for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[reaper.GetSelectedTrack(0, i)] = true end
  local area = string.format('%.10f %.10f ""', a, b)
  for i = 0, reaper.CountTracks(0) - 1 do
    local tr = reaper.GetTrack(0, i)
    reaper.GetSetMediaTrackInfo_String(tr, "P_RAZOREDITS", sel[tr] and area or "", true)
  end
end

local function extend()
  local sel_start, sel_end = readSpan()
  local has_span = sel_start ~= nil and sel_end ~= nil and (sel_end - sel_start) > EPS
  local origin = reaper.GetCursorPosition()

  -- Probe this move's direction (relative moves go forward/backward from anywhere;
  -- absolute jumps land before/after the origin). The probe result also seeds the
  -- first area when none exists yet.
  reaper.Main_OnCommand(MOVE, 0)
  local probed = reaper.GetCursorPosition()

  if probed == origin then
    -- Move could not go any further; leave the area as-is, park at its start.
    if has_span then reaper.SetEditCurPos(sel_start, false, false) end
    return
  end

  local forward = probed > origin
  local new_start, new_end

  if not has_span then
    new_start = math.min(origin, probed)
    new_end = math.max(origin, probed)
  elseif forward then
    -- Grow the END: run the move from the current end.
    reaper.SetEditCurPos(sel_end, false, false)
    reaper.Main_OnCommand(MOVE, 0)
    new_start = sel_start
    new_end = math.max(sel_start, reaper.GetCursorPosition())
  else
    -- Grow the START: run the move from the current start.
    reaper.SetEditCurPos(sel_start, false, false)
    reaper.Main_OnCommand(MOVE, 0)
    new_start = math.min(sel_end, reaper.GetCursorPosition())
    new_end = sel_end
  end

  paint(new_start, new_end)
  reaper.SetEditCurPos(new_start, false, false)  -- transport at the area start
  reaper.Main_OnCommand(42474, 0)                 -- set loop points to razor edit area
  reaper.GetSetRepeat(1)                          -- enable loop, so the area plays looped
end

reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
extend()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
reaper.Undo_EndBlock("${label}", -1)
`
}
