export function renderRazorRepaintScript(opts: { label: string; spec: string }): string {
  const { label, spec } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- Repaint the razor edit (the edit area) over the currently selected tracks,
-- keeping the current time span, then drive transport/loop from it. Used when
-- the vertical (track) dimension of the area changes.

local EPS = 1e-6

local function readSpan()
  for i = 0, reaper.CountTracks(0) - 1 do
    local ok, s = reaper.GetSetMediaTrackInfo_String(reaper.GetTrack(0, i), "P_RAZOREDITS", "", false)
    if ok and s ~= "" then
      local a, b = s:match("([%d%.%-]+)%s+([%d%.%-]+)")
      if a and b then return tonumber(a), tonumber(b) end
    end
  end
  return nil
end

local function repaint()
  local a, b = readSpan()
  if not a or b - a <= EPS then return end
  local sel = {}
  for i = 0, reaper.CountSelectedTracks(0) - 1 do sel[reaper.GetSelectedTrack(0, i)] = true end
  local area = string.format('%.10f %.10f ""', a, b)
  for i = 0, reaper.CountTracks(0) - 1 do
    local tr = reaper.GetTrack(0, i)
    reaper.GetSetMediaTrackInfo_String(tr, "P_RAZOREDITS", sel[tr] and area or "", true)
  end
  reaper.SetEditCurPos(a, false, false)
  reaper.Main_OnCommand(42474, 0)  -- set loop points to razor edit area
  reaper.GetSetRepeat(1)
end

reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
repaint()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
reaper.Undo_EndBlock("${label}", -1)
`
}
