export function renderSelectAreaScript(opts: { label: string; spec: string }): string {
  const { label, spec } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- Materialize the edit area (selected tracks x time range) as split, selected
-- clips, so any operation that acts on selected items applies to the area.
-- Selected tracks are the vertical scope (non-contiguous allowed); the time
-- range is the horizontal scope (zero-width = the edit cursor). This is
-- Separate (B): after it runs, the selected clips ARE the area.

local EPS = 1e-6

local function selectArea()
  local ts_start, ts_end = reaper.GetSet_LoopTimeRange(false, false, 0, 0, false)
  local cursor = reaper.GetCursorPosition()
  local has_ts = ts_end - ts_start > EPS

  local tracks = {}
  local nt = reaper.CountSelectedTracks(0)
  if nt > 0 then
    for i = 0, nt - 1 do tracks[reaper.GetSelectedTrack(0, i)] = true end
  else
    for i = 0, reaper.CountTracks(0) - 1 do tracks[reaper.GetTrack(0, i)] = true end
  end

  local points = has_ts and { ts_start, ts_end } or { cursor }
  table.sort(points)

  for tr in pairs(tracks) do
    for _, p in ipairs(points) do
      local n = reaper.CountTrackMediaItems(tr)
      for i = 0, n - 1 do
        local it = reaper.GetTrackMediaItem(tr, i)
        local pos = reaper.GetMediaItemInfo_Value(it, "D_POSITION")
        local len = reaper.GetMediaItemInfo_Value(it, "D_LENGTH")
        if p > pos + EPS and p < pos + len - EPS then
          reaper.SplitMediaItem(it, p)
          break
        end
      end
    end
  end

  if has_ts then
    reaper.SelectAllMediaItems(0, false)
    for tr in pairs(tracks) do
      local n = reaper.CountTrackMediaItems(tr)
      for i = 0, n - 1 do
        local it = reaper.GetTrackMediaItem(tr, i)
        local pos = reaper.GetMediaItemInfo_Value(it, "D_POSITION")
        local len = reaper.GetMediaItemInfo_Value(it, "D_LENGTH")
        if pos >= ts_start - EPS and pos + len <= ts_end + EPS then
          reaper.SetMediaItemSelected(it, true)
        end
      end
    end
  end
end

reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
selectArea()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
reaper.Undo_EndBlock("${label}", -1)
`
}
