import { debugHook } from '@/debug-runtime'

export function renderSeparateScript(opts: { label: string; spec: string }): string {
  const { label, spec } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- LUNA / Pro Tools "Separate" (B). If a razor edit (the edit area) exists, split
-- at the razor on its tracks (action 40061). Otherwise there is no area, so split
-- at the edit cursor (action 40012) -- the playhead-split fallback. A plain 40061
-- errors ("No time selection active") when neither a razor nor a time selection
-- exists, which is why this is a script rather than a bare action.
${debugHook('separate')}

local function hasRazor()
  for i = 0, reaper.CountTracks(0) - 1 do
    local ok, s = reaper.GetSetMediaTrackInfo_String(reaper.GetTrack(0, i), "P_RAZOREDITS", "", false)
    if ok and s ~= "" then return true end
  end
  return false
end

reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
local razor = hasRazor()
if razor then
  reaper.Main_OnCommand(40061, 0)  -- Split items at time selection or razor edit
else
  reaper.Main_OnCommand(40012, 0)  -- Split items at edit cursor
end
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
reaper.Undo_EndBlock("${label}", -1)
_log("razor=" .. tostring(razor) .. " split=" .. (razor and "40061" or "40012"))
`
}
