// LUNA Tab-to-Transient: native, portable (no ReaTooled dependency). A toggle
// (stored in ExtState) switches between edge-only navigation and
// transient-or-edge navigation, matching Pro Tools' "Tab to Transients" mode.

const NAV_BODY = `
local NS = "LUNA"
local KEY = "tab_to_transient"

-- forward: true = next (item edge 41168 / transient 40375),
--          false = previous (item edge 41167 / transient 40376)
local function nav(forward)
  local useTransient = reaper.GetExtState(NS, KEY) == "1"
  local cursor = reaper.GetCursorPosition()
  local cands = {}

  reaper.SetEditCurPos(cursor, false, false)
  reaper.Main_OnCommand(forward and 41168 or 41167, 0)  -- nearest item edge
  local e = reaper.GetCursorPosition()
  if (forward and e > cursor) or ((not forward) and e < cursor) then cands[#cands + 1] = e end

  if useTransient then
    reaper.SetEditCurPos(cursor, false, false)
    reaper.Main_OnCommand(forward and 40375 or 40376, 0)  -- transient in items
    local t = reaper.GetCursorPosition()
    if (forward and t > cursor) or ((not forward) and t < cursor) then cands[#cands + 1] = t end
  end

  -- pick the candidate nearest to the cursor in the travel direction
  local dest = cursor
  for _, p in ipairs(cands) do
    if dest == cursor then dest = p
    elseif forward and p < dest then dest = p
    elseif (not forward) and p > dest then dest = p end
  end

  reaper.SetEditCurPos(dest, false, false)
  -- a plain move collapses the edit area, like the other nav keys
  reaper.Main_OnCommand(42406, 0)  -- Razor edit: Clear all areas
  reaper.Main_OnCommand(40289, 0)  -- Item: Unselect all items
end
`

export function renderTabNavScript(opts: { label: string; spec: string; forward: boolean }): string {
  const { label, spec, forward } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- Tab-to-Transient navigation (${forward ? 'next' : 'previous'}). Moves the edit
-- cursor to the nearest item edge, or -- when Tab-to-Transient is toggled on --
-- the nearer of the next item edge and the next audio transient. Native REAPER
-- actions only; no ReaTooled dependency.
${NAV_BODY}
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
nav(${forward ? 'true' : 'false'})
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()
reaper.Undo_EndBlock("${label}", -1)
`
}

export function renderTabToggleScript(opts: { label: string; spec: string }): string {
  const { label, spec } = opts
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- Toggle Tab-to-Transient mode. When on, the Tab / Opt+Tab navigation keys stop
-- at audio transients as well as item edges; when off, at item edges only. The
-- state is stored in ExtState and reflected as this action's toggle state so a
-- toolbar button (if assigned) lights up.

local NS = "LUNA"
local KEY = "tab_to_transient"

local on = reaper.GetExtState(NS, KEY) == "1"
local nowOn = not on
reaper.SetExtState(NS, KEY, nowOn and "1" or "0", true)

local _, _, sec, cmd = reaper.get_action_context()
if cmd and cmd ~= -1 then
  reaper.SetToggleCommandState(sec, cmd, nowOn and 1 or 0)
  reaper.RefreshToolbar2(sec, cmd)
end
`
}
