import { debugHook } from '@/debug-runtime'

// LUNA Tab-to-Transient: move the edit cursor to the next/previous audio
// transient. REAPER's transient-navigation actions (40375/40376) only act on
// SELECTED items, so this temporarily selects the items on the selected tracks
// (or all tracks when none are selected), navigates, then restores the prior
// item selection -- so Tab works without pre-selecting a clip and doesn't
// disturb the current selection. Native REAPER actions only; no ReaTooled
// dependency.
export function renderTabTransientScript(opts: { label: string; spec: string; forward: boolean }): string {
  const { label, spec, forward } = opts
  const action = forward ? 40375 : 40376
  return `-- ${label}
-- Generated by reaper-automation from ${spec}. Do not hand-edit.
--
-- Move the edit cursor to the ${forward ? 'next' : 'previous'} audio transient.
-- Transient navigation (40375/40376) only works on selected items, so this
-- temporarily selects the items on the selected tracks (or all tracks if none
-- are selected), runs the navigation, then restores the prior item selection.
${debugHook(`tab_transient_${forward ? 'next' : 'prev'}`)}

-- Returns the number of items it temporarily selected, so the debug line can
-- distinguish "no items to navigate" from "navigated but the cursor held".
local function tabTransient()
  local tracks = {}
  local nsel = reaper.CountSelectedTracks(0)
  if nsel > 0 then
    for i = 0, nsel - 1 do tracks[#tracks + 1] = reaper.GetSelectedTrack(0, i) end
  else
    for i = 0, reaper.CountTracks(0) - 1 do tracks[#tracks + 1] = reaper.GetTrack(0, i) end
  end

  local saved = {}
  for i = 0, reaper.CountSelectedMediaItems(0) - 1 do saved[#saved + 1] = reaper.GetSelectedMediaItem(0, i) end

  reaper.SelectAllMediaItems(0, false)
  local picked = 0
  for _, tr in ipairs(tracks) do
    for i = 0, reaper.CountTrackMediaItems(tr) - 1 do
      reaper.SetMediaItemSelected(reaper.GetTrackMediaItem(tr, i), true)
      picked = picked + 1
    end
  end

  reaper.Main_OnCommand(${action}, 0)

  reaper.SelectAllMediaItems(0, false)
  for _, it in ipairs(saved) do reaper.SetMediaItemSelected(it, true) end
  return #tracks, picked
end

reaper.PreventUIRefresh(1)
local before = reaper.GetCursorPosition()
local ntracks, npicked = tabTransient()
local after = reaper.GetCursorPosition()
reaper.PreventUIRefresh(-1)
reaper.UpdateArrange()

_log(string.format("tracks=%d items=%d cur=%.3f->%.3f moved=%s",
  ntracks, npicked, before, after, tostring(math.abs(after - before) > 1e-9)))
`
}
